vrpn_client_node:
  ros__parameters:
    server: 10.1.1.198
    port: 3883
    frame_id: "world"
    use_server_time: false
    refresh_tracker_frequency: 0.2
    #trackers: ["smallTracker"]
    update_frequency: 30.0
